### ISSUE TITLE
Solve weird global state issues

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-seaborn#1]
Rendering several different charts appears to have global state effects where the settings of one chart affect the rendering of the next one.

I want each chart to be a function of the incoming query string and nothing else.

**Comment by simonw** [comment]
This was supposed to help but doesn't seem to have completely fixed it: https://github.com/simonw/datasette-seaborn/blob/947ce89601dd22b1f5b277a876c601379e3257da/datasette_seaborn/__init__.py#L26-L28

**Comment by simonw** [comment]
https://matplotlib.org/3.3.1/faq/howto_faq.html#how-to-use-matplotlib-in-a-web-application-server suggests avoiding `pyplot` entirely and just using `Figure` - I'm not sure how that transfers to seaborn.

**Comment by simonw** [comment]
https://stackoverflow.com/a/36019091 has some clues.

` matplotlib.pyplot.clf()` clears the current figure.

`matplotlib.pyplot.figure()` starts a new figure.

So maybe using one of those will help.

**Comment by simonw** [comment]
Or https://stackoverflow.com/a/56877082 suggests this:
```python
plot = sns.distplot(data)
plot.get_figure().savefig(path)
plot.get_figure().clf() # this clears the figure
```

**Comment by simonw** [comment]
That didn't completely fix it. I'm seeing weird width errors, where loading a chart with a different width can affect the width of subsequent renders.

I'll build a unit test for this one.

**Comment by simonw** [comment]
Also potentially relevant: https://stackoverflow.com/questions/23969619/plotting-with-seaborn-using-the-matplotlib-object-oriented-interface

**Comment by simonw** [comment]
OK, starting a new figure seems to have solved the size issue. Leaving this ticket open until I'm confident I'm not seeing anything weird happening.

**Comment by simonw** [comment]
Seaborn creator Michael Waskom pointed me here: https://twitter.com/michaelwaskom/status/1304450856444723201 

https://seaborn.pydata.org/tutorial/function_overview.html#axes-level-functions-make-self-contained-plots

> The axes-level functions call [`matplotlib.pyplot.gca()`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.gca.html#matplotlib.pyplot.gca "(in Matplotlib v3.3.1)") internally, which hooks into the matplotlib state-machine interface so that they draw their plots on the "currently-active" axes. But they additionally accept an `ax=` argument, which integrates with the object-oriented interface and lets you specify exactly where each plot should go:
> ```python
> f, axs = plt.subplots(1, 2, figsize=(8, 4), gridspec_kw=dict(width_ratios=[4, 3]))
> sns.scatterplot(data=penguins, x="flipper_length_mm", y="bill_length_mm", hue="species", ax=axs[0])
> sns.histplot(data=penguins, x="species", hue="species", shrink=.8, alpha=.8, legend=False, ax=axs[1])
> f.tight_layout()
> ```

**Comment by simonw** [comment]
https://matplotlib.org/3.1.0/gallery/subplots_axes_and_figures/subplots_demo.html#a-figure-with-just-one-subplot

> `subplots()` without arguments returns a [`Figure`](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure "matplotlib.figure.Figure") and a single [`Axes`](https://matplotlib.org/3.1.0/api/axes_api.html#matplotlib.axes.Axes "matplotlib.axes.Axes").
> 
> This is actually the simplest and recommended way of creating a single Figure and Axes.
> 
> ```python
> fig, ax = plt.subplots()
> ax.plot(x, y)
> ax.set_title('A single plot')
> ```

**Comment by mwaskom** [comment]
If your app works by serially showing one figure, the easiest thing to do is probably to call `plt.close("all")` in the same place as where you're resetting matplotlib defaults and then setting the seaborn theme.

If you need to have multiple figures persist in parallel for an arbitrary duration, it may be a little trickier.

**Comment by simonw** [comment]
Thanks, I'll give that a go!

I tried passing an `ax=` parameter which worked for `histplot` but gave the following error for `relplot`:

    UserWarning: relplot is a figure-level function and does not accept the ax= paramter. You may wish to try scatterplot

**Comment by simonw** [comment]
I'm only returning one figure at a time - I'm hooking up a URL which takes in settings from querystring parameters and returns a PNG.

**Comment by mwaskom** [comment]
Yeah I popped in here because the solution I pointed you to won't work everywhere (as you'll see if you read the surrounding context of the doc page I linked). But it sounds like your situation is pretty simple and you can let seaborn create the figures when it needs to, and just be sure to close them when you're finished.

**Comment by simonw** [comment]
Tests are passing on my laptop but failing in GitHub Actions - maybe there's a difference in the DPI that's being rendered on the two operating systems? Weird.

I'm changing the test to just check that the dimensions don't differ for the same image after loading other images.

**Comment by mwaskom** [comment]
I imagine you want to force matplotlib to use the `Agg` backend.

**Comment by mwaskom** [comment]
Also if you're doing image comparison tests, the default seaborn font is Arial which doesn't exist on the github actions environment, but [can be added](https://github.com/mwaskom/seaborn/blob/master/ci/getmsfonts.sh).

**Comment by simonw** [comment]
This has definitely been solved by running the code in a fresh subprocess, see #4.
