### ISSUE TITLE
Plotly Express could be an easy future target

### ISSUE THREAD

**Issue by jcmkk3** [simonw/datasette-seaborn#7]
I see how Seaborn is a great target for creating visuals that could be built with URL query parameters. If you are not already familiar with it, Plotly has a similar API called [Plotly Express](https://medium.com/plotly/introducing-plotly-express-808df010143d). Since that announcement, it has become part of the main [Plotly.py](https://github.com/plotly/plotly.py) package.

I don't necessarily think that it is a better target, but it could be interesting to consider in the future since the same approach here could probably be easily adapted to create interactive graphics. The biggest win would be tooltips, but also zooming and toggleable legend items. It does have a [really good image exporter](https://medium.com/plotly/introducing-kaleido-b03c4b7b1d81) now, so it could fulfill the static image requirement as well.

I also noticed that you're planning a GUI chart builder. I think that these APIs (single function call) lend themselves really well to a simple GUI. Plotly has created a [much more advanced GUI](https://github.com/plotly/react-chart-editor) that could possibly be used in some sort of workflow after the exploratory visuals with Plotly Express. I think that it would probably be most useful for adding annotations.

**Comment by simonw** [comment]
That looks like it could be a great candidate for a `datasette-plotly` plugin. I already have [datasette-vega](https://github.com/simonw/datasette-vega) which does JavaScript charts using the [Vega Lite](https://vega.github.io/vega-lite/) library, but Plotly looks like it could provide a bunch more options (and their React chart editor does look really nicely done).
